[tool.ruff]
line-length = 120
target-version = "py312"
fix = true
src = ["src"]

include = ["src/**/*.py"]
exclude = [".git", ".venv", "venv", ".mypy_cache", ".ruff_cache",
           "build", "dist", "data", "outputs", "assets", ".ipynb_checkpoints"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

[tool.ruff.lint]
select = ["F", "E", "W", "I", "UP", "B", "SIM", "RUF", "D"]
ignore = ["E203"]
unfixable = ["F401"]
ignore-init-module-imports = true

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true
force-sort-within-sections = true
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
"scripts/**/*.py" = ["D"]
"src/**/__init__.py" = ["F401"]
